# Generated by Django 6.0.6 on 2026-07-05 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['follower', '-created_at'], name='social_foll_followe_31933d_idx'), models.Index(fields=['following', '-created_at'], name='social_foll_followi_6c5306_idx')],
                'constraints': [models.UniqueConstraint(fields=('follower', 'following'), name='unique_pair_follow'), models.CheckConstraint(condition=models.Q(('follower', models.F('following')), _negated=True), name='cannot follow itself')],
            },
        ),
    ]
